import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <meta charSet={"UTF-8"}/>
        <title>PartyChance - Vendez vos biens autrement</title>
        <meta name="description"
              content="Créez une campagne, vendez par tickets, tirez au sort un gagnant sur PartiChance"/>
        <meta name="author" content="PartiChance"/>
    </head>
    <body
        className={`${inter.className} antialiased`}
    >
    {children}
    </body>
    </html>
  );
}