import type { Metadata } from "next";
import "./globals.css";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <meta charSet={"UTF-8"}/>
        <title>PartyChance - Vendez vos biens autrement</title>
        <meta name="description"
              content="Créez une campagne, vendez par tickets, tirez au sort un gagnant sur PartiChance"/>
        <meta name="author" content="PartiChance"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"true"}/>
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
            rel="stylesheet"/>
    </head>
    <body
        className={`font-inter antialiased`}
    >
    {children}
    </body>
    </html>
  );
}